package com.smart.focus.ceoapi.wsdl2.consumptionCostCEO;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2022-11-15T14:20:04.790+09:00
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://0027131779-one-off.sap.com/YHXNC1Z4Y_", name = "YHXNC1Z4Y_ConsumptionCost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface YHXNC1Z4YConsumptionCost {

    @WebMethod(operationName = "Read", action = "http://0027131779-one-off.sap.com/YHXNC1Z4Y_/YHXNC1Z4Y_ConsumptionCost/ReadRequest")
    @WebResult(name = "ConsumptionCostCBOReadByIDResponse_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "ConsumptionCostCBOReadByIDResponse_sync")
    public ConsumptionCostCBOReadByIDResponseMessageSync read(

        @WebParam(partName = "ConsumptionCostCBOReadByIDQuery_sync", name = "ConsumptionCostCBOReadByIDQuery_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
        ConsumptionCostCBOReadByIDQueryMessageSync consumptionCostCBOReadByIDQuerySync
    ) throws StandardFaultMessage_Exception;

    @WebMethod(operationName = "Create", action = "http://0027131779-one-off.sap.com/YHXNC1Z4Y_/YHXNC1Z4Y_ConsumptionCost/CreateRequest")
    @WebResult(name = "ConsumptionCostCBOCreateConfirmation_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "ConsumptionCostCBOCreateConfirmation_sync")
    public ConsumptionCostCBOCreateConfirmationMessageSync create(

        @WebParam(partName = "ConsumptionCostCBOCreateRequest_sync", name = "ConsumptionCostCBOCreateRequest_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
        ConsumptionCostCBOCreateRequestMessageSync consumptionCostCBOCreateRequestSync
    ) throws StandardFaultMessage_Exception;

    @WebMethod(operationName = "Update", action = "http://0027131779-one-off.sap.com/YHXNC1Z4Y_/YHXNC1Z4Y_ConsumptionCost/UpdateRequest")
    @WebResult(name = "ConsumptionCostCBOUpdateConfirmation_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "ConsumptionCostCBOUpdateConfirmation_sync")
    public ConsumptionCostCBOUpdateConfirmationMessageSync update(

        @WebParam(partName = "ConsumptionCostCBOUpdateRequest_sync", name = "ConsumptionCostCBOUpdateRequest_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
        ConsumptionCostCBOUpdateRequestMessageSync consumptionCostCBOUpdateRequestSync
    ) throws StandardFaultMessage_Exception;

    @WebMethod(operationName = "QueryByElements", action = "http://0027131779-one-off.sap.com/YHXNC1Z4Y_/YHXNC1Z4Y_ConsumptionCost/QueryByElementsRequest")
    @WebResult(name = "ConsumptionCostCBOQueryByElementsSimpleByConfirmation_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "ConsumptionCostCBOQueryByElementsSimpleByConfirmation_sync")
    public ConsumptionCostCBOQueryByElementsSimpleByConfirmationMessageSync queryByElements(

        @WebParam(partName = "ConsumptionCostCBOQueryByElementsSimpleByRequest_sync", name = "ConsumptionCostCBOQueryByElementsSimpleByRequest_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
        ConsumptionCostCBOQueryByElementsSimpleByRequestMessageSync consumptionCostCBOQueryByElementsSimpleByRequestSync
    ) throws StandardFaultMessage_Exception;
}
