package com.smart.focus.ceoapi.wsdl2.product_order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-10-29T08:54:06.901+09:00
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://sap.com/xi/A1S/Global", name = "QueryProductionLotISIIn")
@XmlSeeAlso({ ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QueryProductionLotISIIn {

    @WebMethod(operationName = "FindByElements", action = "http://sap.com/xi/A1S/Global/QueryProductionLotISIIn/FindByElementsRequest")
    @WebResult(name = "ProductionLotByElementsResponse_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "ProductionLotByElementsResponse_sync")
    public ProductionLotResponseMessageSync findByElements(

            @WebParam(partName = "ProductionLotByElementsQuery_sync", name = "ProductionLotByElementsQuery_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global") ProductionLotByElementsQueryMessage productionLotByElementsQuerySync)
            throws StandardFaultMessage_Exception;
}
