package com.smart.focus.ceoapi.wsdl2.goodsMovementCEO;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2022-11-15T14:20:04.501+09:00
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://0027131779-one-off.sap.com/YHXNC1Z4Y_", name = "YHXNC1Z4Y_GoodsmovementCEO")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface YHXNC1Z4YGoodsmovementCEO {

    @WebMethod(operationName = "Read", action = "http://0027131779-one-off.sap.com/YHXNC1Z4Y_/YHXNC1Z4Y_GoodsmovementCEO/ReadRequest")
    @WebResult(name = "GoodsMovementCBOReadByIDResponse_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "GoodsMovementCBOReadByIDResponse_sync")
    public GoodsMovementCBOReadByIDResponseMessageSync read(

        @WebParam(partName = "GoodsMovementCBOReadByIDQuery_sync", name = "GoodsMovementCBOReadByIDQuery_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
        GoodsMovementCBOReadByIDQueryMessageSync goodsMovementCBOReadByIDQuerySync
    ) throws StandardFaultMessage_Exception;

    @WebMethod(operationName = "Create", action = "http://0027131779-one-off.sap.com/YHXNC1Z4Y_/YHXNC1Z4Y_GoodsmovementCEO/CreateRequest")
    @WebResult(name = "GoodsMovementCBOCreateConfirmation_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "GoodsMovementCBOCreateConfirmation_sync")
    public GoodsMovementCBOCreateConfirmationMessageSync create(

        @WebParam(partName = "GoodsMovementCBOCreateRequest_sync", name = "GoodsMovementCBOCreateRequest_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
        GoodsMovementCBOCreateRequestMessageSync goodsMovementCBOCreateRequestSync
    ) throws StandardFaultMessage_Exception;

    @WebMethod(operationName = "Update", action = "http://0027131779-one-off.sap.com/YHXNC1Z4Y_/YHXNC1Z4Y_GoodsmovementCEO/UpdateRequest")
    @WebResult(name = "GoodsMovementCBOUpdateConfirmation_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "GoodsMovementCBOUpdateConfirmation_sync")
    public GoodsMovementCBOUpdateConfirmationMessageSync update(

        @WebParam(partName = "GoodsMovementCBOUpdateRequest_sync", name = "GoodsMovementCBOUpdateRequest_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
        GoodsMovementCBOUpdateRequestMessageSync goodsMovementCBOUpdateRequestSync
    ) throws StandardFaultMessage_Exception;

    @WebMethod(operationName = "QueryByElements", action = "http://0027131779-one-off.sap.com/YHXNC1Z4Y_/YHXNC1Z4Y_GoodsmovementCEO/QueryByElementsRequest")
    @WebResult(name = "GoodsMovementCBOQueryByElementsSimpleByConfirmation_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "GoodsMovementCBOQueryByElementsSimpleByConfirmation_sync")
    public GoodsMovementCBOQueryByElementsSimpleByConfirmationMessageSync queryByElements(

        @WebParam(partName = "GoodsMovementCBOQueryByElementsSimpleByRequest_sync", name = "GoodsMovementCBOQueryByElementsSimpleByRequest_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
        GoodsMovementCBOQueryByElementsSimpleByRequestMessageSync goodsMovementCBOQueryByElementsSimpleByRequestSync
    ) throws StandardFaultMessage_Exception;
}
