package com.smart.focus.ceoapi.wsdl2.QueryIdentifiedStocksInBNHQA2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-10-21T15:38:39.596+09:00
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://sap.com/xi/A1S/Global", name = "QueryIdentifiedStocksIn")
@XmlSeeAlso({ ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QueryIdentifiedStocksIn {

    @WebMethod(operationName = "QueryByElements", action = "http://sap.com/xi/A1S/Global/QueryIdentifiedStocksIn/QueryByElementsRequest")
    @WebResult(name = "IdentifiedStockQueryResponseMessage", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "IdentifiedStockQueryResponseMessage")
    public IdentifiedStockQueryResponseMessage queryByElements(

            @WebParam(partName = "IdentifiedStockQueryMessage_sync", name = "IdentifiedStockQueryMessage_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global") IdentifiedStockQueryMessageSync identifiedStockQueryMessageSync)
            throws StandardFaultMessage_Exception;
}
