package com.smart.focus.ceoapi.wsdl2.webServiceTask;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2022-11-30T16:58:41.039+09:00
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://0027131779-one-off.sap.com/Y57MOATJY_", name = "Y57MOATJY_SiteLogisticTaskCBO")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Y57MOATJYSiteLogisticTaskCBO {

    @WebMethod(operationName = "Update", action = "http://0027131779-one-off.sap.com/Y57MOATJY_/Y57MOATJY_SiteLogisticTaskCBO/UpdateRequest")
    @WebResult(name = "MDR_SiteLogisticTaskUpdateConfirmation_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "MDR_SiteLogisticTaskUpdateConfirmation_sync")
    public MDRSiteLogisticTaskUpdateConfirmationMessageSync update(

        @WebParam(partName = "MDR_SiteLogisticTaskUpdateRequest_sync", name = "MDR_SiteLogisticTaskUpdateRequest_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
        MDRSiteLogisticTaskUpdateRequestMessageSync mdrSiteLogisticTaskUpdateRequestSync
    ) throws StandardFaultMessage_Exception;

    @WebMethod(operationName = "QueryByElements", action = "http://0027131779-one-off.sap.com/Y57MOATJY_/Y57MOATJY_SiteLogisticTaskCBO/QueryByElementsRequest")
    @WebResult(name = "MDR_SiteLogisticTaskQueryByElementsSimpleByConfirmation_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "MDR_SiteLogisticTaskQueryByElementsSimpleByConfirmation_sync")
    public MDRSiteLogisticTaskQueryByElementsSimpleByConfirmationMessageSync queryByElements(

        @WebParam(partName = "MDR_SiteLogisticTaskQueryByElementsSimpleByRequest_sync", name = "MDR_SiteLogisticTaskQueryByElementsSimpleByRequest_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
        MDRSiteLogisticTaskQueryByElementsSimpleByRequestMessageSync mdrSiteLogisticTaskQueryByElementsSimpleByRequestSync
    ) throws StandardFaultMessage_Exception;

    @WebMethod(operationName = "Create", action = "http://0027131779-one-off.sap.com/Y57MOATJY_/Y57MOATJY_SiteLogisticTaskCBO/CreateRequest")
    @WebResult(name = "MDR_SiteLogisticTaskCreateConfirmation_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "MDR_SiteLogisticTaskCreateConfirmation_sync")
    public MDRSiteLogisticTaskCreateConfirmationMessageSync create(

        @WebParam(partName = "MDR_SiteLogisticTaskCreateRequest_sync", name = "MDR_SiteLogisticTaskCreateRequest_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
        MDRSiteLogisticTaskCreateRequestMessageSync mdrSiteLogisticTaskCreateRequestSync
    ) throws StandardFaultMessage_Exception;
}
