package com.smart.focus.ceoapi.wsdl2.customer_v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2022-10-31T08:28:26.596+09:00
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://sap.com/xi/A1S/Global", name = "QueryCustomerIn")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QueryCustomerIn {

    @WebMethod(operationName = "FindByCommunicationData", action = "http://sap.com/xi/A1S/Global/QueryCustomerIn/FindByCommunicationDataRequest")
    @WebResult(name = "CustomerByCommunicationDataResponse_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "CustomerByCommunicationDataResponse_sync")
    public CustomerResponseMessageSync findByCommunicationData(

        @WebParam(partName = "CustomerByCommunicationDataQuery_sync", name = "CustomerByCommunicationDataQuery_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
        CustomerByCommunicationDataQueryMessageSync customerByCommunicationDataQuerySync
    ) throws StandardFaultMessage_Exception;

    @WebMethod(operationName = "FindByIdentification", action = "http://sap.com/xi/A1S/Global/QueryCustomerIn/FindByIdentificationRequest")
    @WebResult(name = "CustomerByIdentificationResponse_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "CustomerByIdentificationResponse_sync")
    public CustomerResponseMessageSync findByIdentification(

        @WebParam(partName = "CustomerByIdentificationQuery_sync", name = "CustomerByIdentificationQuery_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
        CustomerByIdentificationQueryMessageSync customerByIdentificationQuerySync
    ) throws StandardFaultMessage_Exception;

    @WebMethod(operationName = "FindByElements", action = "http://sap.com/xi/A1S/Global/QueryCustomerIn/FindByElementsRequest")
    @WebResult(name = "CustomerByElementsResponse_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "CustomerByElementsResponse_sync")
    public CustomerResponseMessageSync findByElements(

        @WebParam(partName = "CustomerByElementsQuery_sync", name = "CustomerByElementsQuery_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
        CustomerByElementsQueryMessageSync customerByElementsQuerySync
    ) throws StandardFaultMessage_Exception;
}
