package com.smart.focus.ceoapi.wsdl2.input_send;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2021-10-06T11:55:37.203+09:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://sap.com/xi/A1S/Global", name = "ManageSiteLogisticsTaskIn")
@XmlSeeAlso({ ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ManageSiteLogisticsTaskIn {

    @WebMethod(operationName = "MaintainBundle_V1", action = "http://sap.com/xi/A1S/Global/ManageSiteLogisticsTaskIn/MaintainBundle_V1Request")
    @WebResult(name = "SiteLogisticsTaskBundleMaintainResponse_sync_V1", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "SiteLogisticsTaskBundleMaintainResponse_sync_V1")
    public SiteLogisticsTaskBundleMaintainResponseMessageSync maintainBundleV1(

            @WebParam(partName = "SiteLogisticsTaskBundleMaintainRequest_sync_V1", name = "SiteLogisticsTaskBundleMaintainRequest_sync_V1", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global") SiteLogisticsTaskMaintainRequestBundleMessage siteLogisticsTaskBundleMaintainRequestSyncV1)
            throws StandardFaultMessage_Exception;
}
