package com.smart.focus.ceoapi.wsdl2.supplier;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-10-07T13:53:08.903+09:00
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://sap.com/xi/A1S/Global", name = "QuerySupplierIn")
@XmlSeeAlso({ ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QuerySupplierIn {

    @WebMethod(operationName = "FindByElements", action = "http://sap.com/xi/A1S/Global/QuerySupplierIn/FindByElementsRequest")
    @WebResult(name = "SupplierByElementsResponse_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "SupplierByElementsResponse_sync")
    public SupplierByElementsResponseMessage findByElements(

            @WebParam(partName = "SupplierByElementsQuery_sync", name = "SupplierByElementsQuery_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global") SupplierByElementsQueryMessageSync supplierByElementsQuerySync)
            throws StandardFaultMessage_Exception;
}
