package com.smart.focus.ceoapi.wsdl2.input_list;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2021-10-06T11:55:36.971+09:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://sap.com/xi/A1S/Global", name = "QuerySiteLogisticsTaskIn")
@XmlSeeAlso({ ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QuerySiteLogisticsTaskIn {

    @WebMethod(operationName = "FindByElements", action = "http://sap.com/xi/A1S/Global/QuerySiteLogisticsTaskIn/FindByElementsRequest")
    @WebResult(name = "SiteLogistcsTaskByElementsResponse_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "SiteLogistcsTaskByElementsResponse_sync")
    public SiteLogisticsTaskResponseMessageSync findByElements(

            @WebParam(partName = "SiteLogisticsTaskByElementsQuery_sync", name = "SiteLogisticsTaskByElementsQuery_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global") SiteLogisticsTaskByElementsQueryMessage siteLogisticsTaskByElementsQuerySync)
            throws StandardFaultMessage_Exception;
}
