package com.smart.focus.ceoapi.wsdl2.material_v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2022-10-31T08:28:26.153+09:00
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://sap.com/xi/A1S/Global", name = "QueryMaterialIn")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QueryMaterialIn {

    @WebMethod(operationName = "FindByElements", action = "http://sap.com/xi/A1S/Global/QueryMaterialIn/FindByElementsRequest")
    @WebResult(name = "MaterialByElementsResponse_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "MaterialByElementsResponse_sync")
    public MaterialByElementsResponseMessageSync findByElements(

        @WebParam(partName = "MaterialByElementsQuery_sync", name = "MaterialByElementsQuery_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
        MaterialByElementsQueryMessageSync materialByElementsQuerySync
    ) throws StandardFaultMessage_Exception;
}
